## ANALYSIS OF PICRUSt2 RESULTS IN R ##

## 1. IMPORT DATA AND CREATE THE PHYLOSEQ OBJECT ##

# Install the microbiomeMarker package if it is not already installed
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
}

BiocManager::install("microbiomeMarker")

# Load the required package
library(microbiomeMarker)

# Import PICRUSt2 outputs into a phyloseq object
# (microbiomeMarker-compatible format)

# Path to the metadata file.
# Metadata must be saved as a tab-delimited text file.
sam_tab <- "./picrust2.metadata.tsv"

# Path to the predicted pathway abundance table generated by PICRUSt2
feature_tab <- "./pathways.out/path_abun_unstrat_descrip.tsv.gz"

# Create the phyloseq object
ps <- import_picrust2(feature_tab, sam_tab, trait = "PATHWAY")

# ALTERNATIVE:
# Load a previously generated phyloseq object containing
# the PICRUSt2 results
ps_picrust <- readRDS("phyloseq_picrust")


## 2. NORMALIZE READ COUNTS ##

# Check the number of reads for each sample
secuencias_inicio <- sample_sums(ps_picrust)
secuencias_inicio

# Determine the minimum sequencing depth and normalize
# all samples to this value
total <- min(sample_sums(ps_picrust))
total

standf = function(x, t = total) round(t * (x / sum(x)))
standf

physeq_normalizado = transform_sample_counts(ps_picrust, standf)
physeq_normalizado

# Verify that all samples have been normalized to approximately
# the same sequencing depth
secuencias_normalizadas_min <- sample_sums(physeq_normalizado)
secuencias_normalizadas_min


## 3. BETA DIVERSITY ANALYSIS ##

# Perform NMDS ordination using Bray–Curtis distance
beta_dist_bray <- ordinate(
  physeq_normalizado,
  method = "NMDS",
  distance = "bray"
)

# Generate the ordination plot.
# Modify the ordination method or distance metric if required.
library(ggrepel)
library(ggdist)

b <- plot_ordination(
  physeq_normalizado,
  beta_dist_bray,
  shape = "Continent",
  color = "Continent"
) +
  theme(
    axis.text.x = element_text(size = 8, color = "black"),
    axis.text.y = element_text(size = 8, color = "black"),
    axis.title.x = element_text(size = 10, color = "black"),
    axis.title.y = element_text(size = 10, color = "black"),
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 9),
    legend.position = "right",
    legend.key.size = unit(0.5, "cm"),
    legend.key.width = unit(1, "cm")
  ) +
  geom_point(size = 3.5) +
  scale_color_manual(values = c(
    "darkolivegreen4",
    "mediumpurple4",
    "sienna3",
    "pink4"
  )) +
  theme(
    legend.title = element_blank(),   # Remove legend title
    plot.title = element_text(
      hjust = 0.5,
      size = 12,
      face = "bold"
    ),
    plot.title.position = "plot"
  ) +
  # Add 95% confidence ellipses around each group
  stat_ellipse(
    aes(group = Continent, color = Continent),
    type = "norm",
    level = 0.95,
    geom = "polygon",
    linetype = 1,
    fill = NA
  )

# Add the plot title
b <- b + ggtitle("Beta diversity")

# Display the plot
print(b)

# Save a high-resolution image
ggsave(
  "NMDS_plot_highres.png",
  plot = b,
  width = 15,
  height = 7,
  dpi = 600
)

# Perform statistical analysis of beta diversity
# using PERMANOVA to test for differences in
# community composition among groups
library(vegan)

phy_bactotutable <- as(
  otu_table(physeq_normalizado),
  "matrix"
)

if (taxa_are_rows(physeq_normalizado)) {
  phy_bactotutable <- t(phy_bactotutable)
}

metadf <- data.frame(sample_data(physeq_normalizado))

beta.dist <- vegdist(
  phy_bactotutable,
  method = "bray"
)

set.seed(36)

beta.dist <- adonis2(
  beta.dist ~ Continent,
  data = metadf
)

# Display the PERMANOVA results,
# including the p-value and R²
beta.dist

## 4. LEfSe ANALYSIS ##

library(microbiomeMarker)

set.seed(36)

mm_lefse <- run_lefse(
  ps_picrust,
  group = "Continent",
  taxa_rank = "Picrust_description",
  kw_cutoff = 0.01
)

mm_lefse

# Access the LEfSe marker table
marker_table <- mm_lefse@marker_table
marker_table

plot <- plot_ef_bar(mm_lefse) +
  scale_fill_manual(values = c(
    "darkolivegreen4",
    "mediumpurple4",
    "sienna3",
    "pink4"
  )) +
  ggtitle("LEfSe")

plot


## 5. ALPHA DIVERSITY ANALYSIS ##

# Calculate alpha diversity indices
alfa_div <- estimate_richness(
  physeq_normalizado,
  measures = c(
    "Shannon",
    "Simpson",
    "Observed"
  )
)

# Load package for statistical comparisons
library(ggpubr)

# Generate all pairwise comparisons among Continent groups
comparisons <- combn(
  unique(sample_data(physeq_normalizado)$Continent),
  2,
  simplify = FALSE
)

p <- plot_richness(
  physeq_normalizado,
  x = "Continent",
  color = "Continent",
  measures = c(
    "Observed",
    "Shannon",
    "Simpson"
  )
)

# Remove the default point layer
p$layers <- p$layers[-1]

plot_alpha_diversity <- p +

  geom_point(size = 5, alpha = 0) +

  geom_boxplot(
    aes(
      x = Continent,
      color = Continent,
      fill = Continent
    ),
    size = 1,
    alpha = 0.3
  ) +

  stat_compare_means(
    comparisons = comparisons,
    label = "p.signif",
    hide.ns = FALSE,
    test = "wilcox.test",
    textsize = 4,
    symnum.args = list(
      cutpoints = c(
        0,
        0.001,
        0.01,
        0.05,
        1
      ),
      symbols = c(
        "***",
        "**",
        "*",
        "ns"
      )
    )
  ) +

  scale_fill_manual(values = c(
    "darkolivegreen3",
    "mediumpurple1",
    "sienna1",
    "thistle2",
    "steelblue1",
    "thistle3"
  )) +

  scale_color_manual(values = c(
    "darkolivegreen",
    "mediumpurple4",
    "sienna3",
    "thistle3",
    "steelblue3",
    "thistle4"
  )) +

  ggtitle("Alpha diversity") +

  labs(
    x = "NA",
    y = ""
  ) +

  theme_classic() +

  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      angle = 90,
      size = 8,
      color = "black"
    ),
    axis.text.y = element_text(
      size = 10,
      color = "black"
    ),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 10),
    legend.position = "bottom",
    legend.key.size = unit(1, "cm"),
    legend.key.width = unit(1, "cm"),
    plot.title = element_text(
      hjust = 0.5,
      size = 12,
      face = "bold"
    )
  )

# Display the alpha diversity plot
print(plot_alpha_diversity)

# Save a high-resolution version of the figure
ggsave(
  filename = "alpha_diversity_plot_highres.pdf",
  plot = plot_alpha_diversity,
  width = 12,
  height = 8,
  dpi = 300,
  units = "in"
)

library(ggpubr)
library(dplyr)

## ALPHA DIVERSITY STATISTICAL RESULTS ##

# Extract alpha diversity values
richness_data <- plot_richness(
  physeq_normalizado,
  x = "Continent",
  measures = c(
    "Observed",
    "Shannon",
    "Simpson"
  )
)$data

# Perform pairwise Wilcoxon tests
# separately for each diversity index
alpha_stats_list <- lapply(
  unique(richness_data$variable),
  function(metric) {

    compare_means(
      value ~ Continent,
      data = filter(
        richness_data,
        variable == metric
      ),
      method = "wilcox.test"
    ) %>%

      mutate(measure = metric)

  }
)

# Combine all statistical results into a single table
alpha_stats <- bind_rows(alpha_stats_list)

# Display the results
print(alpha_stats)

## CREATE A CONTINENT VARIABLE FOR CONTINENT-LEVEL ANALYSES ##

# Convert sample_data into a temporary data frame
# to allow modifications
sample_data_df <- data.frame(sample_data(ps_picrust))

# Create a new "Continent" variable based on the
# country of origin of each sample
sample_data_df$Continent <- with(
  sample_data_df,
  ifelse(
    Country %in% c("USA"), "North America",
    ifelse(
      Country %in% c("Ecuador", "Brazil"), "South America",
      ifelse(
        Country %in% c("Japan", "Indonesia", "China", "Taiwan", "Turkey"), "Asia",
        ifelse(
          Country %in% c("Italy", "Denmark"), "Europe",
          NA
        )
      )
    )
  )
)

# Assign the modified metadata back to the phyloseq object
sample_data(ps_picrust) <- sample_data(sample_data_df)

# Verify the distribution of samples across continents
table(sample_data(ps_picrust)$Continent)


## GENERATE A BAR PLOT OF THE MOST ABUNDANT METABOLIC PATHWAYS ##

### 1. EXTRACT THE ABUNDANCE MATRIX AND METADATA ###

library(phyloseq)
library(dplyr)
library(tidyr)
library(ggplot2)

# Convert the abundance table into a data frame
otu_df <- as.data.frame(otu_table(physeq_normalizado))

# Ensure that rows correspond to samples
if (taxa_are_rows(physeq_normalizado)) {
  otu_df <- t(otu_df)
}

# Add sample identifiers
otu_df <- as.data.frame(otu_df)
otu_df$SampleID <- rownames(otu_df)

# Extract sample metadata
meta_df <- data.frame(sample_data(physeq_normalizado))
meta_df$SampleID <- rownames(meta_df)

# Merge abundance data with metadata
otu_meta <- merge(
  otu_df,
  meta_df,
  by = "SampleID"
)

### 2. CALCULATE THE MEAN ABUNDANCE OF EACH PATHWAY BY CONTINENT ###

# Remove the SampleID column and calculate
# the mean abundance for each continent
ruta_data <- otu_meta %>%
  select(-SampleID) %>%
  group_by(Continent) %>%
  summarise(
    across(where(is.numeric), mean)
  ) %>%
  ungroup()

# Convert the table into long format
ruta_long <- ruta_data %>%
  pivot_longer(
    -Continent,
    names_to = "Ruta",
    values_to = "Abundancia"
  )

### 3. SELECT THE MOST ABUNDANT PATHWAYS ###

# Exclude the "Reads" column (if present)
# and retain the 10 most abundant pathways
top_rutas <- ruta_long %>%
  filter(Ruta != "Reads") %>%
  group_by(Ruta) %>%
  summarise(
    Abundancia_total = sum(Abundancia)
  ) %>%
  arrange(desc(Abundancia_total)) %>%
  slice_head(n = 10) %>%
  pull(Ruta)

ruta_filtrada <- ruta_long %>%
  filter(Ruta %in% top_rutas)

### 4. GENERATE THE BAR PLOT ###

ggplot(
  ruta_filtrada,
  aes(
    x = Continent,
    y = Abundancia,
    fill = Ruta
  )
) +
  geom_bar(
    stat = "identity",
    position = "fill"
  ) +
  scale_y_continuous(
    labels = scales::percent_format()
  ) +
  scale_fill_brewer(
    palette = "Set3"
  ) +
  labs(
    title = "Most abundant metabolic pathways",
    x = "Continent",
    y = "Relative abundance",
    fill = "PICRUSt2 functional pathway"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    ),
    plot.title = element_text(
      hjust = 0.5,
      face = "bold"
    )
  )


